# Generated by Django 5.1.7 on 2025-03-22 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.CharField(max_length=20)),
                ('floor_number', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
                ('equipment_count', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='issue_reports/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fixed', 'Fixed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Infrastructure',
        ),
    ]
