# Generated by Django 5.1.7 on 2025-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_issuereport_delete_infrastructure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuereport',
            old_name='reported_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='issuereport',
            name='equipment_name',
            field=models.CharField(choices=[('Projector', 'Projector'), ('Fan', 'Fan'), ('Sink', 'Sink'), ('Light', 'Light'), ('AC', 'Air Conditioner'), ('Door', 'Door')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='problem_description',
            field=models.CharField(choices=[('Not Working', 'Not Working'), ('Broken', 'Broken'), ('Leaking', 'Leaking'), ('Loose Connection', 'Loose Connection'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='block_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='floor_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
