# Generated by Django 5.1.7 on 2025-03-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_rename_reported_by_issuereport_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuereport',
            old_name='user',
            new_name='reported_by',
        ),
    ]
