# Generated by Django 5.1.7 on 2025-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_block_equipmentcategory_equipment_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='code',
            field=models.CharField(choices=[('A', 'Block A'), ('B', 'Block B'), ('C', 'Block C'), ('D', 'Block D'), ('E', 'Block E')], max_length=1, unique=True),
        ),
    ]
