# Generated by Django 5.1.7 on 2025-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_alter_block_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
