# Generated by Django 5.1.7 on 2025-04-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_alter_block_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
