# Generated by Django 5.1.7 on 2025-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_maintenancerequest_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='title',
            new_name='problem',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='issue_type',
            field=models.CharField(choices=[('ELECTRICAL', 'Electrical issues'), ('PLUMBING', 'Water or pipe-related issues'), ('HVAC', 'heating, ventilation, and air conditioning problems'), ('STRUCTURAL', 'Building structure issues'), ('EQUIPMENT', 'Equipment Failure'), ('FURNITURE', 'Furniture-related issues'), ('OTHER', 'Other')], default='EQUIPMENT', max_length=15),
        ),
    ]
