# Generated by Django 5.1.7 on 2025-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_rename_title_maintenancerequest_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
