# Generated by Django 5.1.7 on 2025-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_maintenancerequest_model_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
